package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strings"
	"unicode"
	"unicode/utf8"
)

const (
	generateMarker = "generate:reset"
	outputFile     = "reset.gen.go"
)

func main() {
	root, err := os.Getwd()
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	if err := run(root); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func run(root string) error {
	packages, err := scanPackages(root)
	if err != nil {
		return err
	}

	for dir, pkg := range packages {
		if len(pkg.structs) == 0 {
			continue
		}
		src, err := renderPackage(pkg)
		if err != nil {
			return fmt.Errorf("%s: %w", dir, err)
		}
		outPath := filepath.Join(dir, outputFile)
		if err := os.WriteFile(outPath, src, 0o644); err != nil {
			return fmt.Errorf("write %s: %w", outPath, err)
		}
		fmt.Printf("generated %s (%d structs)\n", outPath, len(pkg.structs))
	}
	return nil
}

type packageInfo struct {
	name      string
	structs   []structInfo
	resetters map[string]bool
}

type structInfo struct {
	name   string
	fields []*ast.Field
}

func scanPackages(root string) (map[string]*packageInfo, error) {
	packages := make(map[string]*packageInfo)

	err := filepath.WalkDir(root, func(path string, d os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			name := d.Name()
			if shouldSkipDir(name) {
				return filepath.SkipDir
			}
			return nil
		}
		if !strings.HasSuffix(path, ".go") ||
			strings.HasSuffix(path, "_test.go") ||
			filepath.Base(path) == outputFile {
			return nil
		}

		dir := filepath.Dir(path)
		fset := token.NewFileSet()
		file, err := parser.ParseFile(fset, path, nil, parser.ParseComments)
		if err != nil {
			return fmt.Errorf("parse %s: %w", path, err)
		}

		pkg := packages[dir]
		if pkg == nil {
			pkg = &packageInfo{
				name:      file.Name.Name,
				resetters: make(map[string]bool),
			}
			packages[dir] = pkg
		}

		collectResetters(file, pkg.resetters)
		collectMarkedStructs(file, pkg)
		return nil
	})
	if err != nil {
		return nil, err
	}

	for _, pkg := range packages {
		for _, s := range pkg.structs {
			pkg.resetters[s.name] = true
		}
	}
	return packages, nil
}

func shouldSkipDir(name string) bool {
	switch name {
	case ".git", "vendor", "node_modules", ".idea", "testdata":
		return true
	}
	return strings.HasPrefix(name, ".")
}

func collectResetters(file *ast.File, resetters map[string]bool) {
	for _, decl := range file.Decls {
		fn, ok := decl.(*ast.FuncDecl)
		if !ok || fn.Recv == nil || fn.Name == nil || fn.Name.Name != "Reset" {
			continue
		}
		if len(fn.Type.Params.List) != 0 {
			continue
		}
		if fn.Type.Results != nil && len(fn.Type.Results.List) != 0 {
			continue
		}
		if typ := receiverTypeName(fn.Recv); typ != "" {
			resetters[typ] = true
		}
	}
}

func receiverTypeName(recv *ast.FieldList) string {
	if recv == nil || len(recv.List) == 0 {
		return ""
	}
	typ := recv.List[0].Type
	if star, ok := typ.(*ast.StarExpr); ok {
		typ = star.X
	}
	ident, ok := typ.(*ast.Ident)
	if !ok {
		return ""
	}
	return ident.Name
}

func collectMarkedStructs(file *ast.File, pkg *packageInfo) {
	for _, decl := range file.Decls {
		gen, ok := decl.(*ast.GenDecl)
		if !ok || gen.Tok != token.TYPE {
			continue
		}
		for _, spec := range gen.Specs {
			ts, ok := spec.(*ast.TypeSpec)
			if !ok {
				continue
			}
			st, ok := ts.Type.(*ast.StructType)
			if !ok {
				continue
			}
			if !hasGenerateReset(gen.Doc) && !hasGenerateReset(ts.Doc) {
				continue
			}
			pkg.structs = append(pkg.structs, structInfo{
				name:   ts.Name.Name,
				fields: st.Fields.List,
			})
		}
	}
}

func hasGenerateReset(doc *ast.CommentGroup) bool {
	if doc == nil {
		return false
	}
	for _, c := range doc.List {
		text := strings.TrimSpace(strings.TrimPrefix(strings.TrimPrefix(c.Text, "//"), "/*"))
		text = strings.TrimSuffix(text, "*/")
		text = strings.TrimSpace(text)
		if strings.Contains(text, generateMarker) {
			return true
		}
	}
	return false
}

func renderPackage(pkg *packageInfo) ([]byte, error) {
	var b bytes.Buffer
	b.WriteString("// Code generated by cmd/reset; DO NOT EDIT.\n\n")
	b.WriteString("package ")
	b.WriteString(pkg.name)
	b.WriteString("\n\n")

	for i, s := range pkg.structs {
		if i > 0 {
			b.WriteString("\n")
		}
		writeResetMethod(&b, s, pkg.resetters)
	}

	formatted, err := format.Source(b.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format generated code: %w\n%s", err, b.String())
	}
	return formatted, nil
}

func writeResetMethod(b *bytes.Buffer, s structInfo, resetters map[string]bool) {
	recv := receiverName(s.name)
	fmt.Fprintf(b, "func (%s *%s) Reset() {\n", recv, s.name)
	fmt.Fprintf(b, "\tif %s == nil {\n\t\treturn\n\t}\n", recv)

	for _, field := range s.fields {
		names := fieldIdentNames(field)
		for _, name := range names {
			for _, line := range fieldResetLines(recv, name, field.Type, resetters) {
				b.WriteString("\t")
				b.WriteString(line)
				b.WriteString("\n")
			}
		}
	}
	b.WriteString("}\n")
}

func fieldIdentNames(field *ast.Field) []string {
	if len(field.Names) == 0 {
		name := embeddedFieldName(field.Type)
		if name == "" {
			return nil
		}
		return []string{name}
	}
	names := make([]string, 0, len(field.Names))
	for _, ident := range field.Names {
		names = append(names, ident.Name)
	}
	return names
}

func embeddedFieldName(expr ast.Expr) string {
	switch t := expr.(type) {
	case *ast.Ident:
		return t.Name
	case *ast.StarExpr:
		return embeddedFieldName(t.X)
	case *ast.SelectorExpr:
		return t.Sel.Name
	default:
		return ""
	}
}

func fieldResetLines(recv, name string, typ ast.Expr, resetters map[string]bool) []string {
	switch t := typ.(type) {
	case *ast.ArrayType:
		if t.Len == nil {
			return []string{fmt.Sprintf("%s.%s = %s.%s[:0]", recv, name, recv, name)}
		}
		return []string{fmt.Sprintf("%s.%s = %s{}", recv, name, exprString(typ))}
	case *ast.MapType:
		return []string{fmt.Sprintf("clear(%s.%s)", recv, name)}
	case *ast.StarExpr:
		return pointerResetLines(recv, name, t.X, resetters)
	case *ast.Ident:
		if resetters[t.Name] {
			return []string{fmt.Sprintf("%s.%s.Reset()", recv, name)}
		}
		if z, ok := basicZero(t.Name); ok {
			return []string{fmt.Sprintf("%s.%s = %s", recv, name, z)}
		}
		return []string{fmt.Sprintf("%s.%s = %s{}", recv, name, t.Name)}
	case *ast.SelectorExpr:
		typeName := exprString(t)
		return []string{
			fmt.Sprintf("if resetter, ok := any(%s.%s).(interface{ Reset() }); ok {", recv, name),
			"\tresetter.Reset()",
			"} else {",
			fmt.Sprintf("\t%s.%s = %s{}", recv, name, typeName),
			"}",
		}
	case *ast.InterfaceType:
		return []string{
			fmt.Sprintf("if resetter, ok := %s.%s.(interface{ Reset() }); ok && %s.%s != nil {", recv, name, recv, name),
			"\tresetter.Reset()",
			"} else {",
			fmt.Sprintf("\t%s.%s = nil", recv, name),
			"}",
		}
	case *ast.ChanType, *ast.FuncType:
		return []string{fmt.Sprintf("%s.%s = nil", recv, name)}
	default:
		return []string{fmt.Sprintf("%s.%s = %s{}", recv, name, exprString(typ))}
	}
}

func pointerResetLines(recv, name string, elem ast.Expr, resetters map[string]bool) []string {
	switch e := elem.(type) {
	case *ast.Ident:
		if resetters[e.Name] {
			return []string{
				fmt.Sprintf("if resetter, ok := any(%s.%s).(interface{ Reset() }); ok && %s.%s != nil {", recv, name, recv, name),
				"\tresetter.Reset()",
				"}",
			}
		}
		if z, ok := basicZero(e.Name); ok {
			return []string{
				fmt.Sprintf("if %s.%s != nil {", recv, name),
				fmt.Sprintf("\t*%s.%s = %s", recv, name, z),
				"}",
			}
		}
		return []string{
			fmt.Sprintf("if %s.%s != nil {", recv, name),
			fmt.Sprintf("\tif resetter, ok := any(%s.%s).(interface{ Reset() }); ok {", recv, name),
			"\t\tresetter.Reset()",
			"\t} else {",
			fmt.Sprintf("\t\t*%s.%s = %s{}", recv, name, e.Name),
			"\t}",
			"}",
		}
	case *ast.SelectorExpr:
		typeName := exprString(e)
		return []string{
			fmt.Sprintf("if %s.%s != nil {", recv, name),
			fmt.Sprintf("\tif resetter, ok := any(%s.%s).(interface{ Reset() }); ok {", recv, name),
			"\t\tresetter.Reset()",
			"\t} else {",
			fmt.Sprintf("\t\t*%s.%s = %s{}", recv, name, typeName),
			"\t}",
			"}",
		}
	case *ast.ArrayType:
		if e.Len == nil {
			return []string{
				fmt.Sprintf("if %s.%s != nil {", recv, name),
				fmt.Sprintf("\t*%s.%s = (*%s.%s)[:0]", recv, name, recv, name),
				"}",
			}
		}
	case *ast.MapType:
		return []string{
			fmt.Sprintf("if %s.%s != nil {", recv, name),
			fmt.Sprintf("\tclear(*%s.%s)", recv, name),
			"}",
		}
	}

	return []string{
		fmt.Sprintf("if resetter, ok := any(%s.%s).(interface{ Reset() }); ok && %s.%s != nil {", recv, name, recv, name),
		"\tresetter.Reset()",
		"}",
	}
}

func basicZero(name string) (string, bool) {
	switch name {
	case "bool":
		return "false", true
	case "string":
		return `""`, true
	case "int", "int8", "int16", "int32", "int64",
		"uint", "uint8", "uint16", "uint32", "uint64", "uintptr",
		"byte", "rune",
		"float32", "float64",
		"complex64", "complex128":
		return "0", true
	case "error", "any":
		return "nil", true
	default:
		return "", false
	}
}

func receiverName(typeName string) string {
	r, _ := utf8.DecodeRuneInString(typeName)
	if r == utf8.RuneError {
		return "v"
	}
	name := string(unicode.ToLower(r))
	switch name {
	case "i", "j", "k": // частые имена индексов — ок для ресивера
		return name
	}
	return name
}

func exprString(expr ast.Expr) string {
	var b bytes.Buffer
	if err := format.Node(&b, token.NewFileSet(), expr); err != nil {
		return fmt.Sprintf("%s", expr)
	}
	return b.String()
}
