package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestGenerateResetableStruct(t *testing.T) {
	root := t.TempDir()
	pkgDir := filepath.Join(root, "demo")
	if err := os.MkdirAll(pkgDir, 0o755); err != nil {
		t.Fatal(err)
	}

	src := `package demo

// generate:reset
type ResetableStruct struct {
	i     int
	str   string
	strP  *string
	s     []int
	m     map[string]string
	child *ResetableStruct
}
`
	if err := os.WriteFile(filepath.Join(pkgDir, "demo.go"), []byte(src), 0o644); err != nil {
		t.Fatal(err)
	}

	if err := run(root); err != nil {
		t.Fatalf("run: %v", err)
	}

	data, err := os.ReadFile(filepath.Join(pkgDir, outputFile))
	if err != nil {
		t.Fatalf("read generated file: %v", err)
	}
	got := string(data)

	checks := []string{
		"Code generated by cmd/reset",
		"func (r *ResetableStruct) Reset()",
		"if r == nil",
		"r.i = 0",
		`r.str = ""`,
		"if r.strP != nil",
		`*r.strP = ""`,
		"r.s = r.s[:0]",
		"clear(r.m)",
		"interface{ Reset() }",
		"r.child",
	}
	for _, want := range checks {
		if !strings.Contains(got, want) {
			t.Fatalf("generated code missing %q\n%s", want, got)
		}
	}
}
